### ISSUE TITLE
[Mention The Feature]: Tracking Mouse Movement Using JavaScript

### ISSUE THREAD

**Issue by anish013326** [ML-Fusion-Lab/ML-Fusion-Lab-Website#219]
### Describe the solution you'd like.

To implement a feature that tracks mouse movement across the webpage, captures the X and Y coordinates, and utilizes this data to create interactive visual effects.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)
